
server:
  port: 8081
  servlet:
    context-path: /demo
    
spring:
  datasource:
    data-username: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Demo?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
        database: 3
        # redis服务器地址（默认为localhost）
        host: localhost
        # redis端口（默认为6379）
        port: 6379
        # redis访问密码（默认为空）
        password:







